# Generated by Django 2.2.3 on 2019-10-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
