# Generated by Django 2.2.3 on 2019-10-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
    ]
